### PR TITLE
Drop apiextensions

### PR DESCRIPTION
**Pull request by tfussell**
Towards https://github.com/giantswarm/giantswarm/issues/19586

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]

**Comment by fiunchinho** [comment]
So ensuring the `Silence` CRD would no longer be done with `opsctl` but rather using `kubectl apply -f config/crd/monitoring.giantswarm.io_silences.yaml `, right?

**Comment by tfussell** [comment]
> So ensuring the `Silence` CRD would no longer be done with `opsctl` but rather using `kubectl apply -f config/crd/monitoring.giantswarm.io_silences.yaml `, right?

My eventual plan is to use GitOps to manage CRDs. As an intermediate step, I've added support for aggregating CRDs from, for example, `silence-operator` back into `apiextensions` (in https://github.com/giantswarm/apiextensions/pull/829) so we should not see any difference in the CRDs installed with `opsctl ensure crds`.

**Review by fiunchinho — APPROVED** [review]

**Comment by tfussell** [comment]
Still waiting to test this.

**Review by ericgraf — APPROVED** [review]

**Comment by tfussell** [comment]
Tested on `gopher`. I deleted all silences and restarted the operator. The jobs and the operator ran without errors. I found the Silence CRs in the API and corresponding silences in Alertmanager.

**Pull request merged**
