### PR TITLE
add .svc suffix to alertmanager address

### PR DESCRIPTION
**Pull request by bavarianbidi**
To make Silence Operator work behind a corporate proxy, we have to inject the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` variable.

To keep the `NO_PROXY` list as "simple" as possible, following in-cluster-specific values are configured:
`<baseDomain>,<podCIDRBlock>,<serviceCIDRBlock>,<external_k8s_API_IP>`. 

To not change every application to make use of the FQDN (as `baseDomain` could differ) i've decided to add `svc` to the `NO_PROXY` list.

The change of the alertmanager address from `alertmanager-operated.monitoring` to `alertmanager-operated.monitoring.svc` should be a no op for all existing clusters.

towards: https://github.com/giantswarm/roadmap/issues/1423
xref: https://github.com/giantswarm/prometheus-meta-operator/pull/1010

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
I'll try to test it tomorrow

**Comment by bavarianbidi** [comment]
go 1.19 update + `golangci-lint` fix: https://github.com/giantswarm/silence-operator/pull/232

**Review by TheoBrigitte — APPROVED** [review]
LGTM when tested

**Comment by bavarianbidi** [comment]
> LGTM when tested

@TheoBrigitte as i didn't worked with the `silence-operator` so far: how can i test it? what are the test-cases i have to do?

**Pull request merged**
