### PR TITLE
Add Pod monitor

### PR DESCRIPTION
**Pull request by QuentinBisson**
## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by QuantumEnigmaa** [comment]
Why switching to a podmonitor instead of a headless service ?

**Comment by QuentinBisson** [comment]
Because what's the point of the headless service?

**Comment by QuantumEnigmaa** [comment]
> what's the point of the headless service?

It's just there to be used with a servicemonitor. Then my question would most likely be : "why using a podmonitor instead of a servicemonitor ?"

**Comment by QuentinBisson** [comment]
Because there is no reason to have a service as this is not meant to be called :)

**Comment by QuantumEnigmaa** [comment]
Fair enough. Then we should update this doc : https://intranet.giantswarm.io/docs/monitoring/monitoring_of_apps/

**Review by QuantumEnigmaa — APPROVED** [review]

**Comment by QuentinBisson** [comment]
I think we should yes, maybe add an issue in the board?

**Comment by QuentinBisson** [comment]
@marieroque let me know if I can merge :)

**Comment by marieroque** [comment]
`application.giantswarm.io/team` label shouldn't be added to the PodMonitor in order to be scraped by the agent ?

**Comment by marieroque** [comment]
Did you test it on a testing installation ? ;-)

**Comment by QuentinBisson** [comment]
Yes on gauss, but I'm trying that with the annotation now :)

**Pull request merged**
